name: compress

on:
  push:
    branches:
      - algolia-search # default branch name for each repo that docs should be push from

jobs:
  build_docusaurus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        id: build
        run: |
          yarn compress
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docusaurus.tar.gz
          git commit -m "Update compressed docusaurus file"
          git push
