name: compress

on:
  push:
    branches:
      - main
      - staging

jobs:
  compress_docusaurus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        id: build
        run: |
          rm docusaurus.tar.gz; tar --exclude='./docusaurus/node_modules' -czf docusaurus.tar.gz ./docusaurus
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docusaurus.tar.gz
          git commit -m "Update compressed docusaurus file"
          git push
