name: compress

on:
  pull_request:
    branches:
      - staging

jobs:
  remind_about_tarball:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{ sectrets.PAT_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'If you changed anything in the `docusaurus/` directory, remember to also update the docusaurus tarball. In the root of the directory, run `rm docusaurus.tar.gz && tar --exclude='./docusaurus/node_modules' -czf docusaurus.tar.gz ./docusaurus`.'
            })
